name: e_tickets
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  dartz: ^0.10.1
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  intl: ^0.20.2


  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/